### PR TITLE
Reference the Mutiny bindings

### PR DESCRIPTION
**Pull request by jponge**

### CODE REVIEW

**Comment by jponge** [comment]
2021-03-17 14 56 00 localhost 693238672565

**Review by tsegismont — APPROVED** [review]
LGTM

**Comment by michel-kraemer** [comment]
Looks good to me. There's only one issue: it seems Node 15 has updated the `package-lock.json` file to lockfileVersion 2. Since the project uses Node.js 14 (LTS) we should stick with v1. Can you please remove the updated `package-lock.json` from the commit? Thanks.

Also, I'm wondering if we should look for hrefs that start with a slash or if we should do it the other way round (i.e. look for `/^https?:\/\//`). But that might be a matter of taste...

**Review by michel-kraemer — CHANGES_REQUESTED** [review]
Looks good to me. There's only one issue: it seems Node 15 has updated the `package-lock.json` file to lockfileVersion 2. Since the project uses Node.js 14 (LTS) we should stick with v1. Can you please remove the updated `package-lock.json` from the commit? Thanks.

Also, I'm wondering if we should look for hrefs that start with a slash or if we should do it the other way round (i.e. look for `/^https?:\/\//`). But that might be a matter of taste...

**Comment by jponge** [comment]
Sure let me edit/rebase

**Comment by jponge** [comment]
@michel-kraemer Done

**Review by michel-kraemer — APPROVED** [review]

**Comment by michel-kraemer** [comment]
@jponge Thanks! Do you want all reviewers to approve the PR or should I merge now?

**Comment by jponge** [comment]
You can merge now 😉

**Pull request merged**
