### PR TITLE
Vert.x 5 branch

### PR DESCRIPTION
**Pull request by tsegismont**
Commits can be reviewed individually

### CODE REVIEW

**Comment by tsegismont** [comment]
Hi @vietj @michel-kraemer 

I've started a new branch for Vert.x branch. I assume we are all going to contribute to it until v5 is released?
Otherwise, I shall we proceed?

**Comment by vietj** [comment]
I think we will provide a single PR with all changes for web site, so this branch is welcome

**Comment by vietj** [comment]
we also likely try to have a copy of this web site running somewhere else with the vertx 5 branch changes at some point

**Comment by michel-kraemer** [comment]
I can try to extend the GitHub workflow on the weekend so it deploys a preview of the branch too. I'll keep you posted.

**Comment by michel-kraemer** [comment]
@tsegismont I copied your branch over to this repository here and made it so that the website is built for both the master branch and the [vertx5 branch](https://github.com/vertx-web-site/vertx-web-site.github.io/tree/vertx5). The master branch will be published to https://vertx.io and the vertx5 branch to https://vertx.io/vertx5/. Pushing to either branch automatically triggers the build.

I've created a new pull request for the vertx5 branch: https://github.com/vertx-web-site/vertx-web-site.github.io/pull/148

I'm closing this pull request here. Please push to the vertx5 branch in this repository.

@vietj fyi ⬆️

**Comment by vietj** [comment]
very nice @michel-kraemer thanks

**Comment by tsegismont** [comment]
Thank you very much for this @michel-kraemer !

**Pull request closed without merging**
