### PR TITLE
Upload logo of Hose Beijing.

### PR DESCRIPTION
**Pull request by niuhf0452**
Hi, @michel-kraemer,

I have uploaded the new logo. Check it please. 

I'm glad to know you are releasing Vert.x 4.0. Congratulations!

Cheers,
Haifeng Niu

The original PR: https://github.com/vert-x3/vertx-web-site/pull/294
> 
> 
> Thank you for providing your company logo for the "Who's using Vert.x" section on the Vert.x website. We are currently updating the website for Vert.x 4. For this, we are looking for up-to-date versions of all company logos in full color and high resolution.
> 
> If you still want to be listed on the Vert.x website, can you please create a pull request in the new website repository (https://github.com/vertx-web-site/vertx-web-site/pulls) and send us your logo as an **SVG file**? Just include the logo in the pull request - I'll do the rest. Thank you so much! 😊

### CODE REVIEW

**Comment by michel-kraemer** [comment]
Thanks for the quick response! Is this the same logo as the old one? I'm asking, because if I visit https://www.ekuaibao.com/ I see a different logo. Maybe, I have the wrong URL?

**Comment by niuhf0452** [comment]
> Thanks for the quick response! Is this the same logo as the old one? I'm asking, because if I visit https://www.ekuaibao.com/ I see a different logo. Maybe, I have the wrong URL?

No, it's not the same logo as old one. Because the new one is the logo of company, and the old one is the logo of product. We think it's better to put the company logo here.

**Comment by michel-kraemer** [comment]
OK. Great! But the link to the website is still the same?

**Comment by niuhf0452** [comment]
Yes, it's still the same website and link.

**Comment by michel-kraemer** [comment]
Awesome. Thanks!

**Pull request merged**
