### PR TITLE
Include DB2 Client

### PR DESCRIPTION
**Pull request by tsegismont**
For eclipse-vertx/vertx-sql-client#696

### CODE REVIEW

**Comment by tsegismont** [comment]
@michel-kraemer I updated the metadata file and ran `npm run update-docs`.

I can see the BD2 panel in the correct versions in 3.9.1+ root doc pages, but when I click on the link I get a 404. I must have missed something.

**Comment by michel-kraemer** [comment]
@tsegismont You didn't do anything wrong. The problem is that the stack-docs artifact doesn't contain an `index.adoc` file for the vertx-db2-client:

```
$ unzip -l vertx-stack-docs-3.9.1-docs.zip | grep vertx-db2-client
        0  05-15-2020 21:32   vertx-db2-client/
        0  05-15-2020 21:32   vertx-db2-client/java/
     1910  05-15-2020 21:32   vertx-db2-client/java/cursor.adoc
     1093  05-15-2020 21:32   vertx-db2-client/java/connections.adoc
     4218  05-15-2020 21:32   vertx-db2-client/java/dataobjects.adoc
     4281  05-15-2020 21:32   vertx-db2-client/java/queries.adoc
     3300  05-15-2020 21:32   vertx-db2-client/java/transactions.adoc
```

**Comment by michel-kraemer** [comment]
By the way, 3.9.2 does contain a `vertx-db2-client/java/index.adoc` file. However, version 4.0.0.Beta3 does not even contain a `vertx-db2-client` directory at all.

```
$ unzip -l vertx-stack-docs-3.9.2-docs.zip | grep vertx-db2-client
        0  07-16-2020 01:06   vertx-db2-client/
        0  07-16-2020 01:06   vertx-db2-client/java/
     1910  07-16-2020 01:06   vertx-db2-client/java/cursor.adoc
     1093  07-16-2020 01:06   vertx-db2-client/java/connections.adoc
     4259  07-16-2020 01:06   vertx-db2-client/java/dataobjects.adoc
     4281  07-16-2020 01:06   vertx-db2-client/java/queries.adoc
     3300  07-16-2020 01:06   vertx-db2-client/java/transactions.adoc
    11064  07-16-2020 01:06   vertx-db2-client/java/index.adoc

$ unzip -l vertx-stack-docs-4.0.0.Beta3-docs.zip | grep vertx-db2-client
# No output
```

**Comment by tsegismont** [comment]
Thanks Michel, I'll look into this

Le jeu. 8 oct. 2020 à 07:59, Michel Krämer <notifications@github.com> a
écrit :

**Comment by tsegismont** [comment]
@michel-kraemer indeed the `index.adoc` file was added only in 3.9.2. Then I don't why the `vertx-stack-docs` module was updated to include DB2 a while ago, but only in the 3.9 branch. Yesterday I merged a PR that updates `master`.

I have verified that when you choose `3.9.2`, the DB2 client doc is available. So I believe this PR is ready for review.

**Comment by michel-kraemer** [comment]
@tsegismont I'm afraid the problem still persists. If I checkout your branch, run `npm run dev`, and then open http://localhost:3000/docs/3.9.1/vertx-db2-client/java/, I get a 404. However, http://localhost:3000/docs/3.9.2/vertx-db2-client/java/ works. Is that what you intended? I suggest to only add the client to 3.9.2. I can do that for you, if you like.

**Comment by tsegismont** [comment]
@michel-kraemer I updated the PR and it works for 3.x. But now I noticed the link is broken for 4.x :cry: 

I will look into this tomorrow

**Comment by tsegismont** [comment]
@michel-kraemer the db2 docs are not present in the zip file of `beta3` docs. They are present in the zip file of `CR1`.

The problem should be resolved when we bump the 4.x version.

So the PR is ready for review.

**Comment by michel-kraemer** [comment]
Works now. Thanks!

**Pull request merged**
