### PR TITLE
Added API docs link in root docs page

### LINKED ISSUE #50: Add a new API docs link to the docs page root
We have a link to the API docs on each module doc page. That is fine.

It would be great to have a link to the API docs directly at the root of the docs page (just under the page title?)

### PR DESCRIPTION
**Pull request by tsegismont**
Closes #50

### CODE REVIEW

**Comment by michel-kraemer** [comment]
@tsegismont Thanks for the pull request. I've had a look at it and, in my opinion, the table of contents is not the right place to put the API docs link. The table of contents on the left is a short overview of the detailed list of modules on the right, and putting the API docs link there, disconnects the two from each other (in terms of visual perception). I've also tried to move the link to the upper right (where the version number appears when you select a specific version) but it looked more like a subtitle of the main heading ("Documentation") there or even like a separate heading for the main content instead of a link to additional information. I tried to add an icon but that didn't change anything.

At the moment, I don't have a good idea where to put the link. I will keep thinking about it though. Maybe you have a suggestion?

In the meantime, may I ask you why you want to have this link on the index page at all? Does it really have any reasonable benefit? (That's a question I always try to ask myself: take a step back and think about if the additional information, which in this case doesn't really fit anywhere, is actually necessary)

**Comment by tsegismont** [comment]
@michel-kraemer I was looking for the 4.0 API docs and spent some time on the website before I noticed the link was shown on each individual module page.

API docs are not specific to a module in particular, so I believe a link in this page does have some utility. I agree, the TOC is not the best place to show it. I'll try to add it on top in a separate `div`.

**Comment by tsegismont** [comment]
@michel-kraemer I pushed a new commit

**Comment by michel-kraemer** [comment]
This is an interesting approach. I'd like to discuss it with the others.

**Comment by michel-kraemer** [comment]
I beat two birds with one stone: Now that we have the version selector in the docs index header, I was able to also move the API docs link there. It now looks similar to the header of the individual docs pages. Also, we can add more links now if necessary.

**Pull request merged**
